[package]
name = "fujinet-common"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Common utilities and types for FujiNet HAL"
license.workspace = true

[dependencies]
tokio = { workspace = true }
log = { workspace = true }